#test:
#  IP: "192.168.0.101"
#  surroundings: "test"
#  logger_collect_level: INFO
#  logger_print_level: INFO
#  logger_output_level: WARNING
#  browser : "Chrome"
#  phone_model : ["MI 8"]
#  sheet_name: "焕商分佣_test"
#  TestCase: [2]
#  payPassword: "123456"

dev1:
  IP: "192.168.0.102"
  surroundings: "dev1"
  logger_collect_level: INFO
  logger_print_level: INFO
  logger_output_level: WARNING
  browser : "Chrome"
  phone_model : ["MI 8"]
  sheet_name: "焕商分佣_dev1"
  TestCase: [6,10]
  payPassword: "123456"